In [11]:
import os
import pandas as pd

In [34]:
cwd = os.getcwd() # dirname(abspath(__file__))
BASE_DIR = os.path.join(cwd)
DATA_DIR = os.path.join(BASE_DIR, 'data')
CACHE_DIR = os.path.join(BASE_DIR, 'cache')
os.makedirs(CACHE_DIR, exist_ok=True)

In [35]:
for filename in os.listdir(DATA_DIR):
    print(filename)

1999.csv
2000.csv
2001.csv
2002.csv
2003.csv
2004.csv
2005.csv
2006.csv
2007.csv
2008.csv
2009.csv
2010.csv
2011.csv
2012.csv
2013.csv
2014.csv
2015.csv
2016.csv
2017.csv
2018.csv
2019.csv
2020.csv

In [36]:
df = pd.read_csv(os.path.join(DATA_DIR, '2010.csv'))

In [37]:
df.head()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1
0,1,Toy Story 3,"$1,066,969,703","$415,004,880",38.9%,"$651,964,823",61.1%
1,2,Alice in Wonderland,"$1,025,467,110","$334,191,110",32.6%,"$691,276,000",67.4%
2,3,Harry Potter and the Deathly Hallows: Part 1,"$976,536,918","$295,983,305",30.3%,"$680,553,613",69.7%
3,4,Inception,"$828,322,032","$292,576,195",35.3%,"$535,745,837",64.7%
4,5,Shrek Forever After,"$752,600,867","$238,736,787",31.7%,"$513,864,080",68.3%

In [38]:
df['Year'] = 2010

In [39]:
df.head()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,Year
0,1,Toy Story 3,"$1,066,969,703","$415,004,880",38.9%,"$651,964,823",61.1%,2010
1,2,Alice in Wonderland,"$1,025,467,110","$334,191,110",32.6%,"$691,276,000",67.4%,2010
2,3,Harry Potter and the Deathly Hallows: Part 1,"$976,536,918","$295,983,305",30.3%,"$680,553,613",69.7%,2010
3,4,Inception,"$828,322,032","$292,576,195",35.3%,"$535,745,837",64.7%,2010
4,5,Shrek Forever After,"$752,600,867","$238,736,787",31.7%,"$513,864,080",68.3%,2010

In [40]:

my_dataframe = []
csv_file = [x for x in os.listdir(DATA_DIR) if x.endswith(".csv")]
for filename in os.listdir(DATA_DIR):
    print(filename)
    year = filename.replace(".csv","")
    csv_path = os.path.join(DATA_DIR,filename)
    this_df = pd.read_csv(csv_path)
    this_df['filename'] = filename
    this_df['year'] = year
    print(this_df.head(n=1))
    my_dataframe.append(this_df)

1999.csv
   Rank                              Release Group     Worldwide  \
0     1  Star Wars: Episode I - The Phantom Menace  $924,305,084

       Domestic      %       Foreign    %.1  filename  year
0  $431,088,295  46.6%  $493,216,789  53.4%  1999.csv  1999
2000.csv
   Rank           Release Group     Worldwide      Domestic      %  \
0     1  Mission: Impossible II  $546,388,108  $215,409,889  39.4%

        Foreign    %.1  filename  year
0  $330,978,219  60.6%  2000.csv  2000
2001.csv
   Rank                          Release Group     Worldwide      Domestic  \
0     1  Harry Potter and the Sorcerer's Stone  $974,755,371  $317,575,550

       %       Foreign    %.1  filename  year
0  32.6%  $657,179,821  67.4%  2001.csv  2001
2002.csv
   Rank                          Release Group     Worldwide      Domestic  \
0     1  The Lord of the Rings: The Two Towers  $936,689,735  $339,789,881

       %       Foreign    %.1  filename  year
0  36.3%  $596,899,854  63.7%  2002.csv  2002
2003.csv
   Rank                                  Release Group       Worldwide  \
0     1  The Lord of the Rings: The Return of the King  $1,140,682,011

       Domestic      %       Foreign    %.1  filename  year
0  $377,027,325  33.1%  $763,654,686  66.9%  2003.csv  2003
2004.csv
   Rank Release Group     Worldwide      Domestic      %       Foreign    %.1  \
0     1       Shrek 2  $928,760,770  $441,226,247  47.5%  $487,534,523  52.5%

   filename  year
0  2004.csv  2004
2005.csv
   Rank                        Release Group     Worldwide      Domestic  \
0     1  Harry Potter and the Goblet of Fire  $895,921,036  $290,013,036

       %       Foreign    %.1  filename  year
0  32.4%  $605,908,000  67.6%  2005.csv  2005
2006.csv
   Rank                               Release Group       Worldwide  \
0     1  Pirates of the Caribbean: Dead Man's Chest  $1,066,179,725

       Domestic      %       Foreign    %.1  filename  year
0  $423,315,812  39.7%  $642,863,913  60.3%  2006.csv  2006
2007.csv
   Rank                             Release Group     Worldwide      Domestic  \
0     1  Pirates of the Caribbean: At World's End  $960,996,492  $309,420,425

       %       Foreign    %.1  filename  year
0  32.2%  $651,576,067  67.8%  2007.csv  2007
2008.csv
   Rank    Release Group       Worldwide      Domestic      %       Foreign  \
0     1  The Dark Knight  $1,003,045,358  $533,345,358  53.2%  $469,700,000

     %.1  filename  year
0  46.8%  2008.csv  2008
2009.csv
   Rank Release Group       Worldwide      Domestic      %         Foreign  \
0     1        Avatar  $2,744,336,793  $749,766,139  27.3%  $1,994,570,654

     %.1  filename  year
0  72.7%  2009.csv  2009
2010.csv
   Rank Release Group       Worldwide      Domestic      %       Foreign  \
0     1   Toy Story 3  $1,066,969,703  $415,004,880  38.9%  $651,964,823

     %.1  filename  year
0  61.1%  2010.csv  2010
2011.csv
   Rank                                 Release Group       Worldwide  \
0     1  Harry Potter and the Deathly Hallows: Part 2  $1,341,511,219

       Domestic      %       Foreign    %.1  filename  year
0  $381,011,219  28.4%  $960,500,000  71.6%  2011.csv  2011
2012.csv
   Rank Release Group       Worldwide      Domestic    %       Foreign  %.1  \
0     1  The Avengers  $1,518,812,988  $623,357,910  41%  $895,455,078  59%

   filename  year
0  2012.csv  2012
2013.csv
   Rank Release Group       Worldwide      Domestic      %       Foreign  \
0     1        Frozen  $1,280,802,282  $400,738,009  31.3%  $880,064,273

     %.1  filename  year
0  68.7%  2013.csv  2013
2014.csv
   Rank                    Release Group       Worldwide      Domestic      %  \
0     1  Transformers: Age of Extinction  $1,104,054,072  $245,439,076  22.2%

        Foreign    %.1  filename  year
0  $858,614,996  77.8%  2014.csv  2014
2015.csv
   Rank                               Release Group       Worldwide  \
0     1  Star Wars: Episode VII - The Force Awakens  $2,068,223,624

       Domestic      %         Foreign    %.1  filename  year
0  $936,662,225  45.3%  $1,131,561,399  54.7%  2015.csv  2015
2016.csv
   Rank               Release Group       Worldwide      Domestic      %  \
0     1  Captain America: Civil War  $1,153,296,293  $408,084,349  35.4%

        Foreign    %.1  filename  year
0  $745,211,944  64.6%  2016.csv  2016
2017.csv
   Rank                            Release Group       Worldwide  \
0     1  Star Wars: Episode VIII - The Last Jedi  $1,332,539,889

       Domestic      %       Foreign    %.1  filename  year
0  $620,181,382  46.5%  $712,358,507  53.5%  2017.csv  2017
2018.csv
   Rank           Release Group       Worldwide      Domestic      %  \
0     1  Avengers: Infinity War  $2,048,359,754  $678,815,482  33.1%

          Foreign    %.1  filename  year
0  $1,369,544,272  66.9%  2018.csv  2018
2019.csv
   Rank      Release Group       Worldwide      Domestic      %  \
0     1  Avengers: Endgame  $2,797,800,564  $858,373,000  30.7%

          Foreign    %.1  filename  year
0  $1,939,427,564  69.3%  2019.csv  2019
2020.csv
   Rank      Release Group     Worldwide      Domestic      %       Foreign  \
0     1  Bad Boys for Life  $419,074,646  $204,417,855  48.8%  $214,656,791

     %.1  filename  year
0  51.2%  2020.csv  2020

In [41]:
my_dataframe

[     Rank                              Release Group     Worldwide  \
 0       1  Star Wars: Episode I - The Phantom Menace  $924,305,084
 1       2                            The Sixth Sense  $672,806,292
 2       3                                Toy Story 2  $487,059,677
 3       4                                 The Matrix  $463,517,383
 4       5                                     Tarzan  $448,191,819
 ..    ...                                        ...           ...
 381   382                 The Sticky Fingers of Time        $1,610
 382   383                                Summerspell          $984
 383   384               The Underground Comedy Movie          $856
 384   385                                 Port Djema          $783
 385   386                                     Nobody          $488

          Domestic      %       Foreign    %.1  filename  year
 0    $431,088,295  46.6%  $493,216,789  53.4%  1999.csv  1999
 1    $293,506,292  43.6%  $379,300,000  56.4%  1999.csv  1999
 2    $245,852,179  50.5%  $241,207,498  49.5%  1999.csv  1999
 3    $171,479,930    37%  $292,037,453    63%  1999.csv  1999
 4    $171,091,819  38.2%  $277,100,000  61.8%  1999.csv  1999
 ..            ...    ...           ...    ...       ...   ...
 381        $1,610   100%             -      -  1999.csv  1999
 382          $984   100%             -      -  1999.csv  1999
 383          $856   100%             -      -  1999.csv  1999
 384          $783   100%             -      -  1999.csv  1999
 385          $488   100%             -      -  1999.csv  1999

 [386 rows x 9 columns],
      Rank                         Release Group     Worldwide      Domestic  \
 0       1                Mission: Impossible II  $546,388,108  $215,409,889
 1       2                             Gladiator  $460,583,960  $187,705,427
 2       3                             Cast Away  $429,632,142  $233,632,142
 3       4                       What Women Want  $374,111,707  $182,811,707
 4       5                              Dinosaur  $349,822,765  $137,748,063
 ..    ...                                   ...           ...           ...
 372   373                    Stella Does Tricks        $4,224        $4,224
 373   374              Blood, Friends and Money        $3,930        $3,930
 374   375  The Boys in the Band 2000 Re-release        $2,695        $2,695
 375   376                         Better Living        $2,147        $2,147
 376   377                                  Pups        $1,590        $1,590

          %       Foreign    %.1  filename  year
 0    39.4%  $330,978,219  60.6%  2000.csv  2000
 1    40.8%  $272,878,533  59.2%  2000.csv  2000
 2    54.4%  $196,000,000  45.6%  2000.csv  2000
 3    48.9%  $191,300,000  51.1%  2000.csv  2000
 4    39.4%  $212,074,702  60.6%  2000.csv  2000
 ..     ...           ...    ...       ...   ...
 372   100%             -      -  2000.csv  2000
 373   100%             -      -  2000.csv  2000
 374   100%             -      -  2000.csv  2000
 375   100%             -      -  2000.csv  2000
 376   100%             -      -  2000.csv  2000

 [377 rows x 9 columns],
      Rank                                      Release Group     Worldwide  \
 0       1              Harry Potter and the Sorcerer's Stone  $974,755,371
 1       2  The Lord of the Rings: The Fellowship of the Ring  $883,726,270
 2       3                                     Monsters, Inc.  $528,773,250
 3       4                                              Shrek  $484,409,218
 4       5                                     Ocean's Eleven  $450,717,150
 ..    ...                                                ...           ...
 400   401                                       Ginger Snaps        $2,554
 401   402                 Whatever Happened to Harold Smith?        $2,543
 402   403                               Love, Honor and Obey        $1,400
 403   404                      The Last Wave 2001 Re-release          $957
 404   405                            Sorority Girls' Revenge          $582

          Domestic      %       Foreign    %.1  filename  year
 0    $317,575,550  32.6%  $657,179,821  67.4%  2001.csv  2001
 1    $313,364,114  35.5%  $570,362,156  64.5%  2001.csv  2001
 2    $255,873,250  48.4%  $272,900,000  51.6%  2001.csv  2001
 3    $267,665,011  55.3%  $216,744,207  44.7%  2001.csv  2001
 4    $183,417,150  40.7%  $267,300,000  59.3%  2001.csv  2001
 ..            ...    ...           ...    ...       ...   ...
 400        $2,554   100%             -      -  2001.csv  2001
 401        $2,543   100%             -      -  2001.csv  2001
 402        $1,400   100%             -      -  2001.csv  2001
 403          $957   100%             -      -  2001.csv  2001
 404          $582   100%             -      -  2001.csv  2001

 [405 rows x 9 columns],
      Rank                                 Release Group     Worldwide  \
 0       1         The Lord of the Rings: The Two Towers  $936,689,735
 1       2       Harry Potter and the Chamber of Secrets  $878,979,634
 2       3                                    Spider-Man  $821,708,551
 3       4  Star Wars: Episode II - Attack of the Clones  $645,256,452
 4       5                               Men in Black II  $441,818,803
 ..    ...                                           ...           ...
 508   509                           Heartbreak Hospital        $1,480
 509   510                   The Execution of Wanda Jean        $1,386
 510   511                                      Besotted        $1,379
 511   512                                The Jimmy Show        $1,000
 512   513                The Lonely Affair of the Heart          $932

          Domestic      %       Foreign    %.1  filename  year
 0    $339,789,881  36.3%  $596,899,854  63.7%  2002.csv  2002
 1    $261,988,482  29.8%  $616,991,152  70.2%  2002.csv  2002
 2    $403,706,375  49.1%  $418,002,176  50.9%  2002.csv  2002
 3    $302,191,252  46.8%  $343,065,200  53.2%  2002.csv  2002
 4    $190,418,803  43.1%  $251,400,000  56.9%  2002.csv  2002
 ..            ...    ...           ...    ...       ...   ...
 508        $1,480   100%             -      -  2002.csv  2002
 509        $1,386   100%             -      -  2002.csv  2002
 510        $1,379   100%             -      -  2002.csv  2002
 511        $1,000   100%             -      -  2002.csv  2002
 512          $932   100%             -      -  2002.csv  2002

 [513 rows x 9 columns],
      Rank                                      Release Group       Worldwide  \
 0       1      The Lord of the Rings: The Return of the King  $1,140,682,011
 1       2                                       Finding Nemo    $871,014,978
 2       3                                The Matrix Reloaded    $739,412,035
 3       4  Pirates of the Caribbean: The Curse of the Bla...    $654,264,015
 4       5                                     Bruce Almighty    $484,592,874
 ..    ...                                                ...             ...
 501   502      Independent Spirits: Faith Hubley/John Hubley          $1,551
 502   503                        The Ballad of Bering Strait          $1,440
 503   504                                          El Leyton          $1,332
 504   505                                           Exorcism          $1,303
 505   506                                  A House on a Hill            $984

          Domestic      %       Foreign    %.1  filename  year
 0    $377,027,325  33.1%  $763,654,686  66.9%  2003.csv  2003
 1    $339,714,978    39%  $531,300,000    61%  2003.csv  2003
 2    $281,576,461  38.1%  $457,835,574  61.9%  2003.csv  2003
 3    $305,413,918  46.7%  $348,850,097  53.3%  2003.csv  2003
 4    $242,829,261  50.1%  $241,763,613  49.9%  2003.csv  2003
 ..            ...    ...           ...    ...       ...   ...
 501        $1,551   100%             -      -  2003.csv  2003
 502        $1,440   100%             -      -  2003.csv  2003
 503        $1,332   100%             -      -  2003.csv  2003
 504        $1,303   100%             -      -  2003.csv  2003
 505          $984   100%             -      -  2003.csv  2003

 [506 rows x 9 columns],
      Rank                             Release Group     Worldwide  \
 0       1                                   Shrek 2  $928,760,770
 1       2  Harry Potter and the Prisoner of Azkaban  $795,634,069
 2       3                              Spider-Man 2  $788,976,453
 3       4                           The Incredibles  $631,442,092
 4       5                 The Passion of the Christ  $611,486,736
 ..    ...                                       ...           ...
 549   550                                    Shwaas        $1,416
 550   551               800 Bullets 2004 Re-release          $866
 551   552                 Anatomy 2 2004 Re-release          $623
 552   553                           Jesus, You Know          $604
 553   554                                    Tasuma          $479

          Domestic      %       Foreign    %.1  filename  year
 0    $441,226,247  47.5%  $487,534,523  52.5%  2004.csv  2004
 1    $249,541,069  31.4%  $546,093,000  68.6%  2004.csv  2004
 2    $373,585,825  47.4%  $415,390,628  52.6%  2004.csv  2004
 3    $261,441,092  41.4%  $370,001,000  58.6%  2004.csv  2004
 4    $370,274,604  60.6%  $241,212,132  39.4%  2004.csv  2004
 ..            ...    ...           ...    ...       ...   ...
 549        $1,416   100%             -      -  2004.csv  2004
 550          $866   100%             -      -  2004.csv  2004
 551          $623   100%             -      -  2004.csv  2004
 552          $604   100%             -      -  2004.csv  2004
 553          $479   100%             -      -  2004.csv  2004

 [554 rows x 9 columns],
      Rank                                      Release Group     Worldwide  \
 0       1                Harry Potter and the Goblet of Fire  $895,921,036
 1       2       Star Wars: Episode III - Revenge of the Sith  $868,352,530
 2       3  The Chronicles of Narnia: The Lion, the Witch ...  $745,013,115
 3       4                                  War of the Worlds  $603,873,119
 4       5                                          King Kong  $562,363,449
 ..    ...                                                ...           ...
 548   549               Proteus: A Nineteenth Century Vision        $1,246
 549   550                       Spooky House 2005 Re-release          $637
 550   551                                        Steve + Sky          $624
 551   552                            The Comedians of Comedy          $549
 552   553                                     The Dark Hours          $423

          Domestic      %       Foreign    %.1  filename  year
 0    $290,013,036  32.4%  $605,908,000  67.6%  2005.csv  2005
 1    $380,270,577  43.8%  $488,081,953  56.2%  2005.csv  2005
 2    $291,710,957  39.2%  $453,302,158  60.8%  2005.csv  2005
 3    $234,280,354  38.8%  $369,592,765  61.2%  2005.csv  2005
 4    $218,080,025  38.8%  $344,283,424  61.2%  2005.csv  2005
 ..            ...    ...           ...    ...       ...   ...
 548        $1,246   100%             -      -  2005.csv  2005
 549          $637   100%             -      -  2005.csv  2005
 550          $624   100%             -      -  2005.csv  2005
 551          $549   100%             -      -  2005.csv  2005
 552          $423   100%             -      -  2005.csv  2005

 [553 rows x 9 columns],
      Rank                               Release Group       Worldwide  \
 0       1  Pirates of the Caribbean: Dead Man's Chest  $1,066,179,725
 1       2                           The Da Vinci Code    $760,006,945
 2       3                       Ice Age: The Meltdown    $660,998,756
 3       4                               Casino Royale    $606,099,584
 4       5                         Night at the Museum    $574,480,841
 ..    ...                                         ...             ...
 628   629                                      Issues            $783
 629   630                                       Uncut            $762
 630   631                     A New Day in Old Sana'a            $737
 631   632                                       Serum            $440
 632   633                                   Zyzzyx Rd             $30

          Domestic      %       Foreign    %.1  filename  year
 0    $423,315,812  39.7%  $642,863,913  60.3%  2006.csv  2006
 1    $217,536,138  28.6%  $542,470,807  71.4%  2006.csv  2006
 2    $195,330,621  29.6%  $465,668,135  70.4%  2006.csv  2006
 3    $167,445,960  27.6%  $438,653,624  72.4%  2006.csv  2006
 4    $250,863,268  43.7%  $323,617,573  56.3%  2006.csv  2006
 ..            ...    ...           ...    ...       ...   ...
 628          $783   100%             -      -  2006.csv  2006
 629          $762   100%             -      -  2006.csv  2006
 630          $737   100%             -      -  2006.csv  2006
 631          $440   100%             -      -  2006.csv  2006
 632           $30   100%             -      -  2006.csv  2006

 [633 rows x 9 columns],
      Rank                              Release Group     Worldwide  \
 0       1   Pirates of the Caribbean: At World's End  $960,996,492
 1       2  Harry Potter and the Order of the Phoenix  $941,676,843
 2       3                               Spider-Man 3  $894,983,373
 3       4                            Shrek the Third  $813,367,380
 4       5                               Transformers  $709,709,780
 ..    ...                                        ...           ...
 678   679                                        PTU          $849
 679   680                                     Flakes          $778
 680   681                      Notes on Marie Menken          $577
 681   682                                    Obscene          $549
 682   683                              The Last Door          $488

          Domestic      %       Foreign    %.1  filename  year
 0    $309,420,425  32.2%  $651,576,067  67.8%  2007.csv  2007
 1    $292,004,738    31%  $649,672,105    69%  2007.csv  2007
 2    $336,530,303  37.6%  $558,453,070  62.4%  2007.csv  2007
 3    $322,719,944  39.7%  $490,647,436  60.3%  2007.csv  2007
 4    $319,246,193    45%  $390,463,587    55%  2007.csv  2007
 ..            ...    ...           ...    ...       ...   ...
 678             -      -          $849   100%  2007.csv  2007
 679          $778   100%             -      -  2007.csv  2007
 680          $577   100%             -      -  2007.csv  2007
 681             -      -          $549   100%  2007.csv  2007
 682          $488   100%             -      -  2007.csv  2007

 [683 rows x 9 columns],
      Rank                                      Release Group       Worldwide  \
 0       1                                    The Dark Knight  $1,003,045,358
 1       2  Indiana Jones and the Kingdom of the Crystal S...    $790,653,942
 2       3                                      Kung Fu Panda    $631,744,560
 3       4                                            Hancock    $629,443,428
 4       5                                         Mamma Mia!    $609,841,637
 ..    ...                                                ...             ...
 604   605                                      Beat the Drum            $895
 605   606                                         Disfigured            $829
 606   607                    The Rise and Fall of Miss Thang            $581
 607   608                                             Canary            $504
 608   609                                       Rome & Jewel            $470

          Domestic      %       Foreign    %.1  filename  year
 0    $533,345,358  53.2%  $469,700,000  46.8%  2008.csv  2008
 1    $317,101,119  40.1%  $473,552,823  59.9%  2008.csv  2008
 2    $215,434,591  34.1%  $416,309,969  65.9%  2008.csv  2008
 3    $227,946,274  36.2%  $401,497,154  63.8%  2008.csv  2008
 4    $144,130,063  23.6%  $465,711,574  76.4%  2008.csv  2008
 ..            ...    ...           ...    ...       ...   ...
 604             -      -          $895   100%  2008.csv  2008
 605          $829   100%             -      -  2008.csv  2008
 606          $581   100%             -      -  2008.csv  2008
 607          $504   100%             -      -  2008.csv  2008
 608          $470   100%             -      -  2008.csv  2008

 [609 rows x 9 columns],
      Rank                               Release Group       Worldwide  \
 0       1                                      Avatar  $2,744,336,793
 1       2      Harry Potter and the Half-Blood Prince    $933,959,197
 2       3              Ice Age: Dawn of the Dinosaurs    $886,686,817
 3       4         Transformers: Revenge of the Fallen    $836,303,693
 4       5                                        2012    $769,679,473
 ..    ...                                         ...             ...
 513   514  Confessionsofa Ex-Doofus-ItchyFooted Mutha          $1,013
 514   515                   How to Be a Serial Killer            $899
 515   516                      All That Heaven Allows            $170
 516   517                               The Objective             $95
 517   518                                 Dog Eat Dog             $80

          Domestic      %         Foreign    %.1  filename  year
 0    $749,766,139  27.3%  $1,994,570,654  72.7%  2009.csv  2009
 1    $301,959,197  32.3%    $632,000,000  67.7%  2009.csv  2009
 2    $196,573,705  22.2%    $690,113,112  77.8%  2009.csv  2009
 3    $402,111,870  48.1%    $434,191,823  51.9%  2009.csv  2009
 4    $166,112,167  21.6%    $603,567,306  78.4%  2009.csv  2009
 ..            ...    ...             ...    ...       ...   ...
 513        $1,013   100%               -      -  2009.csv  2009
 514          $899   100%               -      -  2009.csv  2009
 515             -      -            $170   100%  2009.csv  2009
 516           $95   100%               -      -  2009.csv  2009
 517           $80   100%               -      -  2009.csv  2009

 [518 rows x 9 columns],
      Rank                                 Release Group       Worldwide  \
 0       1                                   Toy Story 3  $1,066,969,703
 1       2                           Alice in Wonderland  $1,025,467,110
 2       3  Harry Potter and the Deathly Hallows: Part 1    $976,536,918
 3       4                                     Inception    $828,322,032
 4       5                           Shrek Forever After    $752,600,867
 ..    ...                                           ...             ...
 579   580           Carmo, Hit the Road 2010 Re-release          $1,512
 580   581                                         Drool          $1,403
 581   582                                         45365            $853
 582   583                    Shake Hands with the Devil            $594
 583   584                  The Magician 2010 Re-release            $406

          Domestic      %       Foreign    %.1  filename  year
 0    $415,004,880  38.9%  $651,964,823  61.1%  2010.csv  2010
 1    $334,191,110  32.6%  $691,276,000  67.4%  2010.csv  2010
 2    $295,983,305  30.3%  $680,553,613  69.7%  2010.csv  2010
 3    $292,576,195  35.3%  $535,745,837  64.7%  2010.csv  2010
 4    $238,736,787  31.7%  $513,864,080  68.3%  2010.csv  2010
 ..            ...    ...           ...    ...       ...   ...
 579        $1,512   100%             -      -  2010.csv  2010
 580        $1,403   100%             -      -  2010.csv  2010
 581          $853   100%             -      -  2010.csv  2010
 582          $594   100%             -      -  2010.csv  2010
 583          $406   100%             -      -  2010.csv  2010

 [584 rows x 9 columns],
      Rank                                 Release Group       Worldwide  \
 0       1  Harry Potter and the Deathly Hallows: Part 2  $1,341,511,219
 1       2                Transformers: Dark of the Moon  $1,123,794,079

In [42]:
my_entire_dataframe = pd.concat(my_dataframe)

In [43]:
my_entire_dataframe

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,filename,year
0,1,Star Wars: Episode I - The Phantom Menace,"$924,305,084","$431,088,295",46.6%,"$493,216,789",53.4%,1999.csv,1999
1,2,The Sixth Sense,"$672,806,292","$293,506,292",43.6%,"$379,300,000",56.4%,1999.csv,1999
2,3,Toy Story 2,"$487,059,677","$245,852,179",50.5%,"$241,207,498",49.5%,1999.csv,1999
3,4,The Matrix,"$463,517,383","$171,479,930",37%,"$292,037,453",63%,1999.csv,1999
4,5,Tarzan,"$448,191,819","$171,091,819",38.2%,"$277,100,000",61.8%,1999.csv,1999
...,...,...,...,...,...,...,...,...,...
27,28,Burden,"$139,270","$139,270",100%,-,-,2020.csv,2020
28,29,"14 Days, 12 Nights","$122,806","$122,530",99.8%,$276,0.2%,2020.csv,2020
29,30,First Cow,"$101,068","$101,068",100%,-,-,2020.csv,2020
30,31,Run,"$4,052",-,-,"$4,052",100%,2020.csv,2020
31,32,A Quiet Place Part II,$159,-,-,$159,100%,2020.csv,2020

In [44]:
my_entire_dataframe.tail()

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1,filename,year
27,28,Burden,"$139,270","$139,270",100%,-,-,2020.csv,2020
28,29,"14 Days, 12 Nights","$122,806","$122,530",99.8%,$276,0.2%,2020.csv,2020
29,30,First Cow,"$101,068","$101,068",100%,-,-,2020.csv,2020
30,31,Run,"$4,052",-,-,"$4,052",100%,2020.csv,2020
31,32,A Quiet Place Part II,$159,-,-,$159,100%,2020.csv,2020

In [46]:
dataset = os.path.join(CACHE_DIR, 'movies_box_office_dataset.csv')

In [49]:
my_entire_dataframe.to_csv(dataset, index=False)